#!/usr/bin/python

from optparse import OptionParser


# Create option parser

req_doc = """


  module                The module from which maps are to be generated.
  asciis                A list of ascii files with some pixels MISSING. Realizations
                        will be generated on these masks. NOTE: You need to keep the
                        total number of pixels in all asciis down to a few thousand
                        at most!
                        
  NOTES: 
  - All covariate coefficients are set to zero for the purpose of generating realizations.
  - All scalar parameters will be drawn from their priors. If you want to choose specific 
    values, you must set their 'observed' flags.
"""
p = OptionParser('usage: %prog module asciis [options]' + req_doc)
p.add_option('-n','--n-realizations',help='The number of realizations to produce. Defaults to 5.',dest='n',type='int')
p.add_option('-m','--mean',help='The value of the global mean parameter. Defaults to 0.',dest='m',type='float')
p.add_option('-y','--year',help='The DECIMAL YEAR SINCE 2009 at which the realizations should be produced. Required for space-time models.',dest='year',type='float')

p.set_defaults(n=5)
p.set_defaults(m=0)
p.set_defaults(year=None)

(o, args) = p.parse_args()
if len(args) < 2:
    raise ValueError, 'You must supply exactly at least one ascii.'

o.module = args[0]
o.asciis = args[1:]

import matplotlib
matplotlib.use('PDF')
matplotlib.interactive(False)

from map_utils import *
from generic_mbg import *
import tables as tb
import numpy as np
import os, imp, sys, time
import pylab as pl


# Load up given module and load its relevant contents

mod_path, mod_name = os.path.split(o.module)
mod_basename, mod_ext = os.path.splitext(mod_name)
mod_search_path = [mod_path, os.getcwd()] + sys.path
mod = imp.load_module(mod_basename, *imp.find_module(mod_basename, mod_search_path))

for n in ['f_name', 'nugget_name', 'f_has_nugget', 'postproc', 'make_model']:
    try:
        exec("%s=getattr(mod,'%s')"%(n,n))
    except:
        cls,inst,tb = sys.exc_info()
        new_inst = cls('Could not import %s from %s. Tell Anand. Original error message:\n\n\t%s'%(n,mod_name,inst.message))
        raise cls,new_inst,tb

if hasattr(mod,'diag_safe'):
    diag_safe=mod.diag_safe
else:
    diag_safe = False


# Create Model object with dummy lon, lat and possibly t.

d = np.array([0,1])
try:
    M = pm.Model(make_model(np.array([1,0]),np.array([0,1]),d,d,{}))
except:
    M = pm.Model(make_model(np.array([1,0]),np.array([0,1]),d,d,d,{}))


# Create predictive locations

x, unmasked = asc_to_locs(o.mask_name,thin=o.raster_thin, bufsize=o.bufsize)
if not o.year is None:
    x = np.vstack((x.T,o.year*np.ones(x.shape[0]))).T


